---

- 

  hosts: all
  
  vars:
    log_file: "/var/log/cloud-init.log"
    log_file_ubuntu: "/var/log/syslog"
    dump_dir: "/tmp"

  tasks:
    - name: get the log from redhat
      fetch:
        src: "{{log_file}}"
        dest: "{{dump_dir}}"
      when: ansible_distribution == 'RedHat'
    - name: get the log from ubuntu
      fetch:
        src: "{{log_file_ubuntu}}"
        dest: "{{dump_dir}}"
      when: ansible_distribution == 'Ubuntu'