---
##3any playbook start with three dash
- 
##the minues sign indicate a list of items
  hosts: client
  #gather_facts: false
  #3it is the target where my playbook will run
  #varaibles
  #in json the indentation happen with curl braces where as in ansible the indentation happen with two spaces
  vars:
    #variable need to define in key value format
    motd_ubuntu: "Welcome to Ubuntu Linux handler added\n"
    motd_redhat: "Welcome to Redhat Linux handler added\n"
  ##we need to define tasks
  #to define task it start with task block and below the name of the task
  tasks:
    - name: all featured
    #python dictionary
      debug:
        var: 'ansible_facts.eth1.features'
    - name: filter value 
      debug:
        msg: "{{(ansible_facts.eth1.features | dic2items | selectattr ('value','match','on'))}}"