---

- 

  hosts: all
  become: true
  vars:
    path: "/tmp"
  tasks:
    - name: search for file 
      find:
        path: "{{ path }}"
        hidden: true 
        recurse: true 
        file_type: any 
        patterns: '*.txt'
      register: found_text_file 
    - name: print those text file
      debug:
        var: found_text_file
    - name: remove the collected file 
      file: 
        path: "{{item.path}}"
        state: absent 
      with_items: "{{found_text_file }}"
    - name: search for file deleted
      find:
        path: "{{ path }}"
        hidden: true 
        recurse: true 
        file_type: any 
        patterns: '*.txt'
      register: found_text_file 
    - name: print those file if found
      debug:
        var: found_text_file
      