---

- 

  hosts: all
  become: true
  vars:
    mypath: "/tmp/"
  tasks:
    - name: search for file 
      find:
        path: "{{ mypath }}"
        hidden: true 
        recurse: true 
        file_type: any 
        #patterns: '*.txt'
      register: found_text_file 
    - name: remove the collected file 
      file: 
        path: "{{ item.path }}"
        state: absent 
      with_items: "{{found_text_file}}"
    