---

- 

  hosts: all

  tasks:
    
    - name: copy the public key using lookup
      ansible.posix.authorized_key:
        user: root 
        state: present 
        key: "{{lookup('file','~/.ssh/id_rsa.pub')}}"    
    - name: Simple A record (IPV4 address) lookup for example.com
      debug: msg="{{ lookup('dig', 'google.com.')}}"

    - name: "The TXT record for example.org."
      debug: msg="{{ lookup('dig', 'google.com.', 'qtype=TXT') }}"

    - name: "The TXT record for example.org, alternative syntax."
      debug: msg="{{ lookup('dig', 'google.com./TXT') }}"

    - name: use in a loop
      debug: msg="MX record for gmail.com {{ item }}"
      with_items: "{{ lookup('dig', 'gmail.com./MX', wantlist=True) }}"
