---
##3any playbook start with three dash
- 
##the minues sign indicate a list of items
  hosts: all
  #gather_facts: false
  #3it is the target where my playbook will run
  #varaibles
  #in json the indentation happen with curl braces where as in ansible the indentation happen with two spaces
  vars:
    #variable need to define in key value format
    
   
  ##we need to define tasks
  #to define task it start with task block and below the name of the task
  tasks:
    - name: pausing a task 
    #python dictionary
      ansible.builtin.pause:
        seconds: 10
    - name: message 
      debug:
        msg: "the end"