---

- 

  hosts: redhat
 
  tasks:
    - name: ansible set fact for distribution
      ansible.builtin.set_fact:
        mydistribution: "{{'rhel' if (ansible_distribution == 'RedHat') else (ansible_distribution | lower)}}"
    - name: add signing key 
      ansible.builtin.rpm_key:    
        key: "https://download.docker.com/linux/{{mydistribution}}/gpg"
        state: present 
    - name: add the repo in the list 
      ansible.builtin.yum_repository:
        name: docker 
        description: docker repo 
        baseurl: "https://download.docker.com/linux/{{mydistribution}}/$releasever/$basearch/stable"
        enabled: true 
        gpgcheck: true 
        gpgkey: "https://download.docker.com/linux/{{mydistribution}}/gpg"