---

- 

  hosts: all
  vars:
    aws_environment:
      - key: AWS_ACCESS_KEY_ID
        value: AKIAIOSFODNN7EXAMPLE
      - key: AWS_SECRET_ACCESS_KEY
        value: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      - key: AWS_DEFAULT_REGION
        value: us-west-2
  tasks:
    - name: ansible play to retrive environment varaible in linux
      ansible.builtin.debug:
        msg: "{{ansible_env}}"
    - name: second method to get environment varaible
      ansible.builtin.debug:
        msg: "{{(lookup('env','HOME'))}}"
    ###above task show me the environment varaible avaialbe in all the module of your linux system
    ###the second task show me the environment module avaialbe in HOME directory
    ###below task we are permanently adding environment varaible in HOME directory for remote system
    - name: add aws environment varaible in home directory
      lineinfile:
        dest: /etc/environment
        state: present 
        regexp: '^{{item.key}}='
        line: "{{item.key}}={{item.value}}"
      with_items: "{{aws_environment}}"
    - name: second method to get environment varaible for aws
      ansible.builtin.debug:
        msg: "{{ansible_env}}"
      