---

- 

  hosts: all

  tasks:
    - name: ansible play to retrive environment varaible in linux
      ansible.builtin.debug:
        msg: "{{ansible_env}}"
    - name: second method to get environment varaible
      ansible.builtin.debug:
        msg: "{{(lookup('env','HOME'))}}""