---

- 

  hosts: all

  tasks:
    - name: install apache 
      apt:
        name: apache2
        state: present
        update_cache: yes
    - name: Make sure a service unit is running
      ansible.builtin.systemd:
        state: reloaded
        name: apache2

    - name: Print service facts
      ansible.builtin.debug:
         var: ansible_facts.services