---

- 

  hosts: all
  
  vars:
    disable_services:
      - "apache2.service"

  tasks:
    - name: Populate service facts
      ansible.builtin.service_facts:

    - name: Print service facts
      ansible.builtin.service: 
        name: "{{items}}"
        enabled: true
        state: stopped
      when: "item in services"
      with_items: "{{disable_services}}"