- 

  hosts: all
  become: true
  
  tasks:
    - name: search for file 
      ansible.builtin.apt:
        name: "nginx"
        state: present 
        update_cache: yes
    - name: Set logging
      community.general.ufw:
        logging: 'on' 
    - name: we will enable ufw firewall 
      community.general.ufw:
      state: enabled
      policy: "deny"
    - name: add an ufw rule 
      community.general.ufw:
        rule: "allow"
        port: "{{ item }}"
        proto: "tcp"
      with_items:
        - "22"
        - "80"
        - "443"
        - "8080"
      
    