---

- 

  hosts: all
  
  vars:

  tasks:
    - name: import an rpm key from a url
      ansible.builtin.rpm_key:
        state: present
        key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8
      when: ansible_distribution == "RedHat"
    - name: download the rpm file to update 
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
        update_cache: yes 
        state: latest
      when: ansible_distribution == "RedHat"  
    - name: update the ubuntu system 
      apt: 
        update_cache: yes 
      when: ansible_distribution == "Ubuntu"  
    - name: install nginx package
      package:
        name: nginx 
        state: latest 
    - name: patch my redhat system 
      yum: 
        name: patch 
        update_cache: yes
        state: latest 