---

- 

  hosts: all
  
  vars:

  tasks:
    - name: import an rpm key from a url
      ansible.builtin.rpm_key:
        state: present
        key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8
      when: ansible_distribution == "RedHat"
    - name: down the rpm file to update 
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-next-release-latest-8.noarch.rpm
        update_cache: yes 
        state: latest
      when: ansible_distribution == "RedHat"  