---

- 

  hosts: all
  
  vars:

  tasks:
    - name: import an rpm key from a url
      ansible.builtin.rpm_key:
        state: present
        key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8
      when: ansible_distribution == "RedHat"
      tags: rpmkey 
    - name: download the rpm file to update 
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
        update_cache: yes 
        state: latest
      when: ansible_distribution == "RedHat"  
      tags: rpm 
    - name: update the ubuntu system 
      apt: 
        update_cache: yes 
      when: ansible_distribution == "Ubuntu"  
    - name: install nginx package
      package:
        name: nginx 
        state: latest 
      tags: package 
    - name: patch my redhat system 
      yum: 
        name: patch 
        update_cache: yes
        state: latest
      tags: patch 
      when: ansible_distribution == "RedHat"
    - name: create a directory called as site available 
      file:
        path: /etc/nginx/sites-available
        state: directory #file link
    - name: create another directory called as site enable 
      file:
        path: /etc/nginx/sites-enabled
        state: directory
    - name: copy the default config 
      copy:
        src: files/nginx-default.conf
        dest: /etc/nginx/sites-available/default
    - name: create a symb link from siteavaiale to site enable 
      file:
        src: /etc/nginx/sites-available/default 
        dest: /etc/nginx/sites-enabled/default 
        state: link 
    - name: create an nginx html directory 
      file: 
        path: /usr/share/nginx/html
        state: directory 
    - name: template for test page 
      template:
        src: templates/index.html.j2
        dest: /usr/share/nginx/index.html
        mode: 0644
    - name: add port 80 for redhat system
      ansible.posix.firewalld:
        service: http
        permanent: yes
        state: enabled
      when: ansible_distribution == "RedHat"
    - name: restart nginx 
      service:
        name: nginx 
        state: restarted
      notify: Check HTTP Service 
  handlers:
    - name: Check HTTP Service 
      uri:
        url: http://{{ansible_default_ipv4.address}}
        status_code: 200
